jwt:
  key-pair: jwt.pem
  issuer: rebue
  # 签名有效时间
  expiration-duration: 120m

spring:
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1

logging:
  level:
    root: info
    rebue: trace
    '[org.apache.http]': warn
    '[com.netflix.discovery]': warn
    '[org.springframework.context.event.SimpleApplicationEventMulticaster]': warn
    '[org.springframework.dao]': debug
    '[org.springframework.cloud]': warn
    '[com.alibaba.nacos.client.config.impl.ClientWorker]': warn