jwt:
  # 因为算法为HS512，所以至少需要有512个bit，也就是64个Byte
  sign-key: ABCabc123ABCabc123ABCabc123ABCabc123ABCabc123ABCabc123ABCabc123中文乱码ABCabc123
  # 签发者
  issuer: rebue
  # 过期时间间隔(默认是30m)
#  expiration-duration: 3s # 单元测试时使用

# 生成workid使用
curator:
  connect-string: zoo1:2181,zoo2:2181,zoo3:2181

spring:
  redis:
    password: xxxxxxxx
    sentinel:
      master: mymaster
      nodes:
        - redis_sentinel1:26379
        - redis_sentinel2:26379
        - redis_sentinel3:26379
  cloud:
    sentinel:
      enabled: false
  # 链路追踪可视化服务器
  zipkin:
    base-url: zipkin:9411
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1

logging:
  level:
    root: info
    rebue: trace
    '[org.apache.http]': warn
    '[com.netflix.discovery]': warn
    '[org.springframework.context.event.SimpleApplicationEventMulticaster]': warn
    '[org.springframework.dao]': debug
    '[org.springframework.cloud]': warn
    '[com.alibaba.nacos.client.config.impl.ClientWorker]': warn