jwt:
  key-pair: jwt-dev-key-pair.pem
  issuer: rebue
  expiration-duration: 30m

# 生成workid使用
curator:
  connect-string: zoo1:2181,zoo2:2181,zoo3:2181

spring:
  redis:
    password: xxxxxxxx
    sentinel:
      master: mymaster
      nodes:
        - redis_sentinel1:26379
        - redis_sentinel2:26379
        - redis_sentinel3:26379
  cloud:
    sentinel:
      enabled: false