DROP TABLE IF EXISTS `OSS_OBJ`;
CREATE TABLE OSS_OBJ(
    ID BIGINT UNSIGNED NOT NULL   COMMENT '对象ID' ,
    OBJ_NAME VARCHAR(512) NOT NULL   COMMENT '对象名称' ,
    OBJ_GROUP VARCHAR(30) NOT NULL   COMMENT '对象分组' ,
    OBJ_TYPE VARCHAR(30) NOT NULL   COMMENT '对象类型' ,
    OBJ_SIZE BIGINT UNSIGNED NOT NULL   COMMENT '对象大小' ,
    URL VARCHAR(512) NOT NULL   COMMENT '对象URL' ,
    CREATOR_ID BIGINT UNSIGNED NOT NULL   COMMENT '创建人的账户ID' ,
    CREATOR_ORG_ID BIGINT UNSIGNED    COMMENT '创建人的组织ID' ,
    CREATE_DATETIME DATETIME NOT NULL   COMMENT '创建时间' ,
    PRIMARY KEY (ID)
) COMMENT = '对象 ';

ALTER TABLE OSS_OBJ COMMENT '对象';
