# 配置中心的配置
scx:
  gateway:
    # 发送消息的超时时间(发送添加请求和响应日志的消息时使用)
    send-timeout: 5000
    multipart:
      max-file-size:
        specifies:
          - url: "POST:/rac/account/upload-avatar"
            limit: 200KB

 # 生成workid使用
curator:
  connect-string: zoo1:2181,zoo2:2181,zoo3:2181

spring:
  cloud:
    sentinel:
      transport:
        dashboard: sentinel-dashboard:80
    gateway:
      discovery:
        locator:
          filters:
            - StripPrefix=1
            - name: SignPre
              args:
                filter-urls:
                  - "'/ctid/**'"
            - name: JwtPre
              args:
                filter-urls:
                  - "'*:/sgn/**'"
                  - "'*:/rac/**'"
                  - "'*:/cap/**'"
                  - "'*:/oss/**'"
                  - "'*:/wxx/**'"
                ignore-urls:
                  - "'*:/oss/**'"
                  - "'*:/wxx/**'"
                  - "'POST:/rac/sign-in/**'"
                  - "'*:/orp/**'"
                  - "'POST:/cap/**'"
                  - "'GET:/rac/account/get-cur-account-info'"
                  #统一应用平台账户基础权限
                  - "'GET:/oap/app/list-and-tripartite'"
                  - "'GET:/rac/dic/**'"
                  - "'GET:/rac/account/get-cur-account-info'"
                  - "'GET:/rac/account/get-by-id'"
                  - "'GET:/rac/account/exist-mobile-by-id'"
                  - "'GET:/rac/op-log/page'"
                  - "'PUT:/rac/account/modify-sign-in-by-old-pswd'"
                  - "'POST:/rac/account/upload-avatar'"
                  - "'POST:/rac/account/bind-mobile'"
                  - "'POST:/rac/sms/**'"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  # 链路追踪可视化服务器
  zipkin:
    base-url: zipkin:9411
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1

logging:
  level:
    root: info
    rebue: trace
    '[org.apache.http]': warn
    '[com.netflix.discovery]': warn
    '[org.springframework.context.event.SimpleApplicationEventMulticaster]': warn
    '[org.springframework.dao]': debug
    '[org.springframework.cloud]': warn
    '[com.alibaba.nacos.client.config.impl.ClientWorker]': warn
