# 配置中心的配置
scx:
  gateway:
    # 发送消息的超时时间(发送添加请求和响应日志的消息时使用)
    send-timeout: 1000
    multipart:
      max-file-size:
        default-limit: 1MB
        specifies:
          - url: POST:/rac/account/upload-avatar
            limit: 500KB

spring:
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1
  # 链路追踪可视化服务器
  zipkin:
    # 服务器地址
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: sr
          uri: http://127.0.0.1:20010
          predicates:
          - Path=/admin-web/**
          filters:
          - name: JwtPre
        - id: welcome
          uri: http://127.0.0.1:20010
          predicates:
          - Path=/
          filters:
          - name: JwtPre

oidc:
  redirect-uri: http://auth.maiyuesoft.com/oap-svr/oidc/authorize?scope=openid&response_type=code&client_id=unified-auth&state=st&redirect_uri=http%3A%2F%2Fauth.maiyuesoft.com%2Forp-svr%2Foidc%2Fcallback