# 配置中心的配置
scx:
  gateway:
    # 发送消息的超时时间(发送添加请求和响应日志的消息时使用)
    send-timeout: 1000
    multipart:
      max-file-size:
        default-limit: 1MB
        specifies:
          - url: POST:/rac/account/upload-avatar
            limit: 75KB

spring:
  cloud:
    gateway:
      discovery:
        locator:
          filters:
            - StripPrefix=1
            - name: SignPre
              args:
                filter-urls:
                  - "'/ctid/**'"
            - name: JwtPre
              args:
                filter-urls:
                  - "'*:/sgn/**'"
                  - "'*:/rac/**'"
                  - "'*:/cap/**'"
                  - "'*:/oss/**'"
                  - "'*:/wxx/**'"
                ignore-urls:
                  - "'*:/oss/**'"
                  - "'*:/wxx/**'"
                  - "'POST:/rac/sign-in/**'"
                  - "'POST:/cap/captcha/**'"
                  - "'GET:/rac/account/get-cur-account-info'"
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1
  # 链路追踪可视化服务器
  zipkin:
    # 服务器地址
    base-url: http://zipkin:9411