version: "3.9"
services:
  gateway-server:
    image: nnzbz/spring-boot-app
    ports:
      - 10085:10085
    environment:
      # 最好使用此设定时区，其它镜像也可以使用
      - TZ=CST-8
      - PROG_ARGS=--spring.profiles.active=prod
      # - PROG_ARGS=--spring.profiles.active=hwy
      # - JAVA_OPTS=-Xms150M -Xmx150M
    volumes:
      # 配置文件目录
      - /usr/local/gateway-server/config/:/usr/local/myservice/config/
      - /usr/local/gateway-server/gateway-server-1.2.4.jar:/usr/local/myservice/myservice.jar
    deploy:
      replicas: 3
      
networks:
  default:
    external: true
    name: rebue
