version: "3.9"
services:
  svr:
    image: nnzbz/spring-boot-app
    hostname: rac-svr
    init: true
    environment:
      - PROG_ARGS=--spring.profiles.active=prod
      # 启用SkyWalking Agent
      - ENABLE_SKYWALKING_AGENT=true
      # Agent的项目名称
      - SW_AGENT_NAME=rac-svr
      # SkyWalking OAP 服务器的地址
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:12800
      #- JAVA_OPTS=-Xms100M -Xmx100M
    volumes:
      # 初始化脚本
      - /usr/local/rac-svr/init.sh:/usr/local/myservice/init.sh:z
      # SkyWalking Agent的配置文件
      - /usr/local/rac-svr/config/apm-trace-ignore-plugin.config:/usr/local/skywalking/agent/config/apm-trace-ignore-plugin.config:z
      # 配置文件目录
      - /usr/local/rac-svr/config/:/usr/local/myservice/config/:z
      # 运行的jar包
      - /usr/local/rac-svr/rac-svr-1.2.5.jar:/usr/local/myservice/myservice.jar:z
    deploy:
      placement:
        constraints:
          # 部署的节点指定是app角色的
          - node.labels.role==app
      replicas: 1
networks:
  default:
    external: true
    name: rebue
