# 配置中心中的配置
#登保配置  
level-protect: 
  lock-duration: 60
  password-minLength: 6
  password-character: 1
  password-tips: false
  password-errors: 5
  password-doverdue: 90
minio:
  endpoint: http://minio:9000  
# 文件路径是否需要全路径还是只需要去除Ip的相对路径地址
# true 全路径http://127.0.0.1:9000/oss-svr/***
# false 相对路径 /oss-svr/**
  urlPrefixBool: false
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# 生成workid使用
curator:
  connect-string: zoo1:2181,zoo2:2181,zoo3:2181

spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql1:3306/rac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: xxxxxxxx
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql2:3306/rac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: xxxxxxxx
    rules:
      readwrite-splitting:
        data-sources:
          masterslave:
            write-data-source-name: master
            read-data-source-names: slave
  flyway:
    enabled: false
    clean-disabled: true
  liquibase:
    #enabled: false
    # 升级数据库的配置文件的地址
    #change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    url: jdbc:mysql://mysql1:3306/rac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    user: root
    password: xxxxxxxx
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    password: xxxxxxxx
    sentinel:
      master: mymaster
      nodes:
        - redis_sentinel1:26379
        - redis_sentinel2:26379
        - redis_sentinel3:26379
  cloud:
    sentinel:
      enabled: false
  # 链路追踪可视化服务器
  zipkin:
    base-url: zipkin:9411
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1

logging:
  level:
    root: info
    rebue: trace
    '[org.apache.http]': warn
    '[com.netflix.discovery]': warn
    '[org.springframework.context.event.SimpleApplicationEventMulticaster]': warn
    '[org.springframework.dao]': debug
    '[org.springframework.cloud]': warn
    '[com.alibaba.nacos.client.config.impl.ClientWorker]': warn