# 开发环境的配置
debug: true
minio:
  endpoint: http://172.20.14.125:9000
# 文件路径是否需要全路径还是只需要去除Ip的相对路径地址
# true 全路径http://127.0.0.1:9000/oss-svr/***
# false 相对路径 /oss-svr/**
  urlPrefixBool: true
  accessKey: minioadmin
  secretKey: minioadmin
server:
  # 自定义端口号，方便开发测试
  port: 9605

spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/rac
        type: com.zaxxer.hikari.HikariDataSource
        username: rac
        password: rac
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/rac
        type: com.zaxxer.hikari.HikariDataSource
        username: rac
        password: rac 
    rules:
      readwrite-splitting:
        data-sources:
          masterslave:
            write-data-source-name: master
            read-data-source-names: slave     
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/rac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: root
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      enabled: false
  sleuth:
    enabled: false

curator:
  connect-string: 127.0.0.1:2181
