oidc:
  client-id: unified-auth
  client-secret: 123456
  token-endpoint: http://127.0.0.1:13080/oap-svr/oap/token
  redirect-uri: http://127.0.0.1:13080/orp-svr/orp/callback
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx1PdAIB021x1DExsXPO7hgzE0EASZiFoQh5F4X0H8lZrdCVG+Qk6ek9Aowp4bUnAf93PiM4A0L9zjck8jOedd6gbRPifsqdtDWx4jlfy7nGUd3LUF3wFH7VwNlCTkMucetnxFuNtGMVM8rz/YCXAYv6pYi56vq7BWlNh373qhVhqxY6SBs2qo5hxWe/zpv6CqxAXSKjcCJVLQhe7jnfWGJbLPnwSTK/b/jVtic/e9rD7EdSfPF3rt5TSqEdsX0EHHUSLFLUbpDOQzSBXdyGsAHQdeytr/i5AVi3BOKV9k5h1ricIZta6KD7krxZk60o70fWDF+0DQVQD5upWEeRLdQIDAQAB
  login-url: http://127.0.0.1/admin-web/unified-auth/sign-in/unified

orp:
  state-cache-expiration: PT1M
  strategies:
    ding-talk:
      is-check-state: true
      clients:
        - id: dingsahvlqybvb44jd50
          name: dwdfw
          secret: hWt9A-ebYcR30DoXqJHLcka62jpR3ZKMc6GFizNW-5xczbahLr0yf7plEO7ewm80
        - id: dingsahvlqybvb44jd55
          name: dwdfw
          secret: hWt9A-ebYcR30DoXqJHLcka62jpR3ZKMc6GFizNW-5xczbahLr0yf7plEO7ewm85
    wechat-open:
      is-check-state: true
      clients:
        - id: wxc9bcdf70da391cdd
          name: dwdfw
          secret: 4a215a29ccf5d91c2c8ea2af12a57e93
        - id: wxc9bcdf70da391cdd5
          secret: 4a215a29ccf5d91c2c8ea2af12a57e935
    oidc:
      is-check-state: true
      clients:
        - id: unified-auth
          secret: 123456
      extras:
        call-uri: http://127.0.0.1:13080
        redirect-uri: http://127.0.0.1:13080
        client-id: unified-auth
