# 配置中心中的配置
oidc:
  client-id: unified-auth
  client-secret: 123456
  token-endpoint: http://10.200.101.16:3456/oap-svr/oap/token
  redirect-uri: https://auth.nnxy.edu.cn/orp-svr/orp/callback
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx1PdAIB021x1DExsXPO7hgzE0EASZiFoQh5F4X0H8lZrdCVG+Qk6ek9Aowp4bUnAf93PiM4A0L9zjck8jOedd6gbRPifsqdtDWx4jlfy7nGUd3LUF3wFH7VwNlCTkMucetnxFuNtGMVM8rz/YCXAYv6pYi56vq7BWlNh373qhVhqxY6SBs2qo5hxWe/zpv6CqxAXSKjcCJVLQhe7jnfWGJbLPnwSTK/b/jVtic/e9rD7EdSfPF3rt5TSqEdsX0EHHUSLFLUbpDOQzSBXdyGsAHQdeytr/i5AVi3BOKV9k5h1ricIZta6KD7krxZk60o70fWDF+0DQVQD5upWEeRLdQIDAQAB
  login-url: https://auth.nnxy.edu.cn/admin-web/#/sign-in/unified

orp:
  state-cache-expiration: PT5M
  strategies:
    ding-talk:
      is-check-state: true
      clients:
        - id: dingxxxxxxxxxxxxxxxx
          secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    wechat-open:
      is-check-state: true
      clients:
        - id: wxxxxxxxxxxxxxxxxx
          secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
orp:
  state-cache-expiration: PT1M
  strategies:
    ding-talk:
      is-check-state: true
      clients:
        - id: dingsahvlqybvb44jd50
          secret: hWt9A-ebYcR30DoXqJHLcka62jpR3ZKMc6GFizNW-5xczbahLr0yf7plEO7ewm80
    wechat-open:
      is-check-state: true
      clients:
        - id: wxc9bcdf70da391cdd
          secret: 4a215a29ccf5d91c2c8ea2af12a57e93
# 生成workid使用
curator:
  connect-string: zookeeper_zoo1:2181,zookeeper_zoo2:2181,zookeeper_zoo3:2181

spring:
    redis:
    password: xxxxxxxx
  sentinel:
    master: mymaster
    nodes:
      - redis_sentinel1:26379
      - redis_sentinel2:26379
      - redis_sentinel3:26379
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1
  # 链路追踪可视化服务器
  zipkin:
    # 服务器地址
    base-url: http://zipkin:9411
