# 配置中心中的配置
spring:
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1
  # 链路追踪可视化服务器
  zipkin:
    # 服务器地址
    base-url: http://zipkin:9411

oidc:
  client-id: unified-auth
  client-secret: 123456
  token-endpoint: http://127.0.0.1/oap-svr/oidc/token
  redirect-uri: http://127.0.0.1/orp-svr/oidc/callback
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx1PdAIB021x1DExsXPO7hgzE0EASZiFoQh5F4X0H8lZrdCVG+Qk6ek9Aowp4bUnAf93PiM4A0L9zjck8jOedd6gbRPifsqdtDWx4jlfy7nGUd3LUF3wFH7VwNlCTkMucetnxFuNtGMVM8rz/YCXAYv6pYi56vq7BWlNh373qhVhqxY6SBs2qo5hxWe/zpv6CqxAXSKjcCJVLQhe7jnfWGJbLPnwSTK/b/jVtic/e9rD7EdSfPF3rt5TSqEdsX0EHHUSLFLUbpDOQzSBXdyGsAHQdeytr/i5AVi3BOKV9k5h1ricIZta6KD7krxZk60o70fWDF+0DQVQD5upWEeRLdQIDAQAB
  login-url: http://127.0.0.1/admin-web/#/sign-in/unified
  cookie-domain: 127.0.0.1