version: "3.9"
services:
  gateway-server:
    image: nnzbz/spring-boot-app:1.0.3
    ports:
      - 10085:10085
    environment:
      # 最好使用此设定时区，其它镜像也可以使用
      - TZ=CST-8
    volumes:
      # 配置文件目录
      - /usr/local/gateway-server/config/:/usr/local/myservice/config/
      - /usr/local/gateway-server/gateway-server-1.2.4.jar:/usr/local/myservice/myservice.jar
networks:
  default:
    external: true
    name: rebue
