# 配置中心中的配置
msg:
  sms:
    #短信平台jiguang/baidu
    sms-platform: jiguang
    #接口是否模拟短信
    simulation: true
    #secret
    masterSecret: e92f7f27dbd27bf0f1157c61
    #key
    appkey: 823ebe289daa183f863eee73
    #模板
    tempId: 202223
    #签名
    signId: 20492
  email:
    #模板邮箱发送请求地址
    email-templet-endpoint: https://api.ums.jiguang.cn/v1/template/sent
    #普通邮箱发送请求地址
    email-ordinary-endpoint: https://api.ums.jiguang.cn/v1/sent
    simulation: false
    #key
    app-key: 10001275A644497
    #secret
    app-secret: c3a12648939a4cde9ca2e4a5
    #模板
    tempId: 10522    

# 生成workid使用
curator:
  connect-string: zoo1:2181,zoo2:2181,zoo3:2181

spring:
  mail:
   #连接登录的smtp服务器地址
    host: smtp.qq.com
    protocol: smtp
    jndi-name: mail/Session
    #mtp登陆的账号、密码 ；帐号需开启smtp登陆功能支持
    username: 1343782084@qq.com
    #访问SMTP服务时需要提供的密码,不是邮箱登陆密码，一般都有独立smtp的登陆密码
    password: lahuhmmiawojgefa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3500
          writetimeout: 4000
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: xxxxxxxx
    virtual-host: /
  redis:
    password: xxxxxxxx
    sentinel:
      master: mymaster
      nodes:
        - redis_sentinel1:26379
        - redis_sentinel2:26379
        - redis_sentinel3:26379
  cloud:
    sentinel:
      enabled: false
  # 链路追踪可视化服务器
  zipkin:
    base-url: zipkin:9411
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1

logging:
  level:
    root: info
    rebue: trace
    '[org.apache.http]': warn
    '[com.netflix.discovery]': warn
    '[org.springframework.context.event.SimpleApplicationEventMulticaster]': warn
    '[org.springframework.dao]': debug
    '[org.springframework.cloud]': warn
    '[com.alibaba.nacos.client.config.impl.ClientWorker]': warn
 
    