# 配置中心中的配置
msg:
  sms:
    #短信平台jiguang/baidu
    sms-platform: jiguang
    simulation: true
    app-key: 823ebe289daa183f863eee73
    app-secret: e92f7f27dbd27bf0f1157c61
    tempId: 202223
    signId: 20492
  email:
    email-templet-endpoint: https://api.ums.jiguang.cn/v1/template/sent
    email-ordinary-endpoint: https://api.ums.jiguang.cn/v1/sent
    simulation: false
    app-key: 10001275A644497
    app-secret: c3a12648939a4cde9ca2e4a5
    tempId: 10522

spring:
  mail:
   #连接登录的smtp服务器地址
    host: smtp.qq.com
    protocol: smtp
    jndi-name: mail/Session
    #mtp登陆的账号、密码 ；帐号需开启smtp登陆功能支持
    username: 1343782084@qq.com
    #访问SMTP服务时需要提供的密码,不是邮箱登陆密码，一般都有独立smtp的登陆密码
    password: lahuhmmiawojgefa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3500
          writetimeout: 4000
          starttls:
            enable: true
            required: true
    
