# 配置中心中的配置
msg:
  sms:
    masterSecret: e92f7f27dbd27bf0f1157c61
    appkey: 823ebe289daa183f863eee73
    tempId: 202223
    signId: 20492
# 生成workid使用
curator:
  connect-string: zoo1:2181,zoo2:2181,zoo3:2181

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cap-svr?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: cap
    password: cap
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: xxxxxxxx
    virtual-host: /
  redis:
    password: xxxxxxxx
    sentinel:
      master: mymaster
      nodes:
        - redis_sentinel1:26379
        - redis_sentinel2:26379
        - redis_sentinel3:26379
  cloud:
    sentinel:
      enabled: false
  # 链路追踪可视化服务器
  zipkin:
    base-url: zipkin:9411
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1

logging:
  level:
    root: info
    rebue: trace
    '[org.apache.http]': warn
    '[com.netflix.discovery]': warn
    '[org.springframework.context.event.SimpleApplicationEventMulticaster]': warn
    '[org.springframework.dao]': debug
    '[org.springframework.cloud]': warn
    '[com.alibaba.nacos.client.config.impl.ClientWorker]': warn
 
    