server:
  port: 30010

demo-configurations:
  client-id: third-party-demo
  client-secret: 123456
  issuer: third-party-demo-issuer
  auth-uri: http://127.0.0.1/oap-svr/oidc/authorize?scope=openid&response_type=code&client_id=third-party-demo&state=tr&redirect_uri=http%3A%2F%2Fthe-localhost:30010%2Fcallback
  redirect: http://the-localhost:30010/callback
  token-endpoint: http://127.0.0.1/oap-svr/oidc/token