DROP TABLE RRL_REQ_LOG;
CREATE TABLE RRL_REQ_LOG(
    ID BIGINT UNSIGNED NOT NULL   COMMENT 'ID' ,
    EVENT_ID VARCHAR(30) NOT NULL   COMMENT '事件ID' ,
    SESSION_ID BIGINT UNSIGNED NOT NULL   COMMENT '会话ID' ,
    METHOD VARCHAR(10) NOT NULL   COMMENT '请求方法' ,
    SCHEME VARCHAR(10) NOT NULL   COMMENT '请求协议' ,
    HOST VARCHAR(30) NOT NULL   COMMENT '请求主机' ,
    PORT INT NOT NULL   COMMENT '请求端口号' ,
    PATH VARCHAR(512) NOT NULL   COMMENT '请求路径' ,
    URI VARCHAR(512) NOT NULL   COMMENT '请求地址' ,
    HEADERS VARCHAR(3076)    COMMENT '请求头' ,
    CONTENT_TYPE VARCHAR(30)    COMMENT '内容类型' ,
    COOKIES VARCHAR(2048)    COMMENT 'COOKIES' ,
    QUERY_PARAMS VARCHAR(2048)    COMMENT '请求查询参数' ,
    BODY TEXT    COMMENT '请求主体' ,
    CREATE_TIMESTAMP BIGINT UNSIGNED NOT NULL   COMMENT '请求时间戳' ,
    PRIMARY KEY (ID)
) COMMENT = '请求日志 ';

ALTER TABLE RRL_REQ_LOG COMMENT '请求日志';
DROP TABLE RRL_RESP_LOG;
CREATE TABLE RRL_RESP_LOG(
    ID BIGINT UNSIGNED NOT NULL   COMMENT 'ID' ,
    EVENT_ID VARCHAR(30) NOT NULL   COMMENT '事件ID' ,
    SESSION_ID BIGINT UNSIGNED NOT NULL   COMMENT '会话ID' ,
    STATUS_CODE CHAR(3) NOT NULL   COMMENT '响应状态码' ,
    HEADERS VARCHAR(3076) NOT NULL   COMMENT '响应头部' ,
    COOKIES VARCHAR(2048)    COMMENT 'COOKIES' ,
    BODY VARCHAR(2048)    COMMENT '响应主体' ,
    CREATE_TIMESTAMP BIGINT UNSIGNED NOT NULL   COMMENT '响应时间戳' ,
    PRIMARY KEY (ID)
) COMMENT = '响应日志 ';

ALTER TABLE RRL_RESP_LOG COMMENT '响应日志';
