version: "3.9"
services:
  svr:
    image: nnzbz/spring-boot-app
    hostname: gateway-server
    init: true
    environment:
      - PROG_ARGS=--spring.profiles.active=prod
      - ENABLE_SKYWALKING_AGENT=true
      #- JAVA_OPTS=-Xms100M -Xmx100M
    volumes:
      # 初始化脚本
      - /usr/local/gateway-server/init.sh:/usr/local/myservice/init.sh:z
      # SkyWalking Agent的配置文件
      - /usr/local/gateway-server/config/apm-trace-ignore-plugin.config:/usr/local/skywalking/agent/config/apm-trace-ignore-plugin.config:z
      # 配置文件目录
      - /usr/local/gateway-server/config/:/usr/local/myservice/config/:z
      # 运行的jar包
      - /usr/local/gateway-server/gateway-server-1.2.5.jar:/usr/local/myservice/myservice.jar:z
    deploy:
      placement:
        constraints:
          # 部署的节点指定是web角色的
          - node.labels.role==web
      replicas: 1
networks:
  default:
    external: true
    name: rebue
