# 配置中心中的配置
captcha:
  #滑动验证，底图路径，不配置将使用默认图片
  #支持全路径
  ##支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
  jigsaw: classpath:images/jigsaw
  #点击验证，底图路径，不配置将使用默认图片
  ##支持全路径
  ##支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/pic-click
  pic-click: classpath:images/pic-click
  #验证码类型default两种都实例化。
  cache-type: redis
 #local定时清除过期缓存(单位秒),设置为0代表不执行
  timing-clear: 180
  #验证码类型default两种都实例化。
  type: default
  #汉字统一使用Unicode,保证程序通过@value读取到是中文，可通过这个在线转换 https://tool.chinaz.com/tools/unicode.aspx 中文转Unicode
  #右下角水印文字(我的水印)
  water-mark: .
  # 右下角水印字体(不配置时，默认使用文泉驿正黑)
  # 由于宋体等涉及到版权，我们jar中内置了开源字体【文泉驿正黑】
  # 方式一：直接配置OS层的现有的字体名称，比如：宋体
  # 方式二：自定义特定字体，请将字体放到工程resources下fonts文件夹，支持ttf\ttc\otf字体
  water-font: WenQuanZhengHei.ttf
  # 点选文字验证码的文字字体(文泉驿正黑)
  font-type: WenQuanZhengHei.ttf
  # 校验滑动拼图允许误差偏移量(默认5像素)
  slip-offset: 5
  # aes加密坐标开启或者禁用(true|false)
  aes-status: true
  # 滑动干扰项(0/1/2) 1.2.2版本新增
  interference-options: 1
  #点选字体样式 默认Font.BOLD
  font-style: 1
  #点选字体字体大小
  font-size: 25
  history-data-clear-enable: false
  # 接口请求次数一分钟限制是否开启 true|false
  req-frequency-limit-enable: false
  # 验证失败5次，get接口锁定
  req-get-lock-limit: 5
  # 验证失败后，锁定时间间隔,s
  req-get-lock-seconds: 360
  # check接口一分钟内请求数限制
  req-get-minute-limit: 30 
  # check接口一分钟内请求数限制
  req-check-minute-limit: 30
# 生成workid使用
curator:
  connect-string: 127.0.0.1:2181

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    sentinel:
      enabled: false
  # 链路追踪可视化服务器
  zipkin:
    base-url: zipkin:9411
  # 链路追踪采集器
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1